[package]
edition = "2018"
name = "ra_prof"
version = "0.1.0"
authors = ["rust-analyzer developers"]
publish = false
license = "MIT OR Apache-2.0"

[lib]
doctest = false

[dependencies]
ra_arena = { path = "../ra_arena", version = "0.1.0" }
once_cell = "1.3.1"
backtrace = { version = "0.3.44", optional = true }
cfg-if = "0.1.10"
libc = "0.2.73"

[target.'cfg(target_os = "linux")'.dependencies]
perf-event = "0.4"

[features]
cpu_profiler = []

# Uncomment to enable for the whole crate graph
# default = [ "backtrace" ]
# default = [ "cpu_profiler" ]
