[package]
edition = "2018"
name = "ra_def"
version = "0.1.0"
authors = ["rust-analyzer developers"]

[dependencies]
arrayvec = "0.4.10"
log = "0.4.5"
relative-path = "0.4.0"
rustc-hash = "1.0"
ena = "0.13"
once_cell = "1.0.1"

ra_syntax = { path = "../ra_syntax" }
ra_arena = { path = "../ra_arena" }
ra_cfg = { path = "../ra_cfg" }
ra_db = { path = "../ra_db" }
mbe = { path = "../ra_mbe", package = "ra_mbe" }
tt = { path = "../ra_tt", package = "ra_tt" }
test_utils = { path = "../test_utils" }
ra_prof = { path = "../ra_prof" }

[dev-dependencies]
insta = "0.11.0"
