[workspace]
members = [ "crates/*", "xtask/" ]

[profile.dev]
debug = 1 # only line info

[profile.release]
incremental = true
debug = 1 # only line info

[patch.'crates-io']
rowan = { git = "https://github.com/cad97/rowan", branch = "boxed-tokens" }
