[package]
edition = "2018"
name = "ra_hir"
version = "0.1.0"
authors = ["rust-analyzer developers"]
license = "MIT OR Apache-2.0"

[lib]
doctest = false

[dependencies]
log = "0.4.8"
rustc-hash = "1.1.0"
either = "1.5.3"
arrayvec = "0.5.1"

itertools = "0.9.0"

stdx = { path = "../stdx", version = "0.1.0" }
ra_syntax = { path = "../ra_syntax", version = "0.1.0" }
ra_db = { path = "../ra_db", version = "0.1.0" }
ra_prof = { path = "../ra_prof", version = "0.1.0" }
hir_expand = { path = "../ra_hir_expand", version = "0.1.0", package = "ra_hir_expand" }
hir_def = { path = "../ra_hir_def", version = "0.1.0", package = "ra_hir_def" }
hir_ty = { path = "../ra_hir_ty", version = "0.1.0", package = "ra_hir_ty" }
