[package]
name = "paths"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
