[package]
edition = "2018"
name = "ra_proc_macro"
version = "0.1.0"
authors = ["rust-analyzer developers"]
publish = false

[lib]
doctest = false

[dependencies]
ra_tt = { path = "../ra_tt" }
ra_mbe = { path = "../ra_mbe" }
serde_derive = "1.0.104"
serde = "1.0.104"
serde_json = "1.0.48"
log = "0.4.8"
crossbeam-channel = "0.4.0"

smol_str = { version = "0.1.15", features = ["serde"] }