[package]
edition = "2018"
name = "ra_lsp_server"
version = "0.1.0"
authors = ["rust-analyzer developers"]

[dependencies]
threadpool = "1.7.1"
relative-path = "0.4.0"
failure = "0.1.4"
failure_derive = "0.1.4"
serde_json = "1.0.34"
serde = { version = "1.0.83", features = ["derive"] }
crossbeam-channel = "0.3.5"
flexi_logger = "0.11.0"
log = "0.4.3"
url_serde = "0.2.0"
lsp-types = { version = "0.57.0", features = ["proposed"] }
rustc-hash = "1.0"
parking_lot = "0.7.0"

ra_vfs = "0.2.0"
thread_worker = { path = "../thread_worker" }
ra_syntax = { path = "../ra_syntax" }
ra_text_edit = { path = "../ra_text_edit" }
ra_ide_api = { path = "../ra_ide_api" }
ra_arena = { path = "../ra_arena" }
gen_lsp_server = { path = "../gen_lsp_server" }
ra_project_model = { path = "../ra_project_model" }
ra_prof = { path = "../ra_prof" }

[dev-dependencies]
tempfile = "3"
test_utils = { path = "../test_utils" }

[features]
jemalloc = [ "ra_ide_api/jemalloc" ]
