[package]
edition = "2018"
name = "stdx"
version = "0.1.0"
authors = ["rust-analyzer developers"]
license = "MIT OR Apache-2.0"

[lib]
doctest = false

[dependencies]
# Think twice before adding anything here
