[package]
edition = "2018"
name = "ra_macros"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]

[dependencies]
rustc-hash = "1.0.0"
smol_str = "0.1.9"
join_to_string = "0.1.3"
