[package]
edition = "2018"
name = "thread_worker"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]

[dependencies]
drop_bomb = "0.1.0"
crossbeam-channel = "0.3.4"
log = "0.4.3"

